### ISSUE TITLE
Create a project document

### ISSUE THREAD

**Issue by Shreyanand** [aicoe-aiops/time-series#1]
As a data scientist, I would like to create a project document for this project following the organisations format. This document will be used as a reference point for the project's description any major ideas. 

- [ ] Acceptance: Project document

**Comment by Shreyanand** [comment]
First [draft](https://docs.google.com/document/d/1dq1bNjY6TWrfdJPmQoQ235SHTqqZpVIxCkX6gQNLf6M/edit#)

**Comment by MichaelClifford** [comment]
Does the existence of the current README complete this card?

**Comment by Shreyanand** [comment]
> Does the existence of the current README complete this card?

It's not in the same format but I think it provides a good and peer reviewed base for the following notebooks. I'm closing this issue for now.
