### ISSUE TITLE
Setting relative links 

### ISSUE THREAD

**Issue by Shreyanand** [aicoe-aiops/time-series#11]
Currently, the table of content links in the Readme ([PR link](https://github.com/aicoe-aiops/time-series/pull/10/)) work for the github repository. I'll be using this same post for  the operate first website. How do I format these links so that they point to the right page on the website?

**Comment by MichaelClifford** [comment]
@Shreyanand see [this](https://github.com/operate-first/operate-first.github.io#linking) section of the operate first readme. But generally, if you are using relative links that work on github they should work on operate-first too.

**Comment by Shreyanand** [comment]
Thanks Michael, fixed them :+1:
