### ISSUE TITLE
Add image to operate first ODH

### ISSUE THREAD

**Issue by Shreyanand** [aicoe-aiops/time-series#13]
As a consumer of this work, I would like to experiment with the time series analysis methods on a running notebook.

Acceptance

- [x] Make a repository on quay ([Issue](https://github.com/operate-first/continuous-delivery/issues/8))
- [x] Image on quay
- [x] Quay image running on operate first ODH

**Comment by MichaelClifford** [comment]
@Shreyanand this is also done now, yeah?

**Comment by Shreyanand** [comment]
> @Shreyanand this is also done now, yeah?

Yup!
