### ISSUE TITLE
Define a problem statement

### ISSUE THREAD

**Issue by Shreyanand** [aicoe-aiops/time-series#6]
As a data scientist, I would like to apply the time series introduction material to an actual problem statement.
Comments and ideas are welcome.

- [ ] Acceptance: one valid problem statement to work on.

**Comment by MichaelClifford** [comment]
What is the purpose of this project? To connect with real Prometheus data, then demo a number of time series analysis techniques similar to the categorical encoding work? If so, wouldn't a single "problem statement" artificially narrow the scope? Have you defined what techniques/things you want to cover in the "time series introduction material" yet? 

You might want to define a couple of problem statements like:

* Revisit some of the [Prometheus anomaly detection](https://github.com/AICoE/prometheus-anomaly-detector) work to **explore a number of time-series forecasting methods**. 
* Look at this [summit demo](https://github.com/TreeinRandomForest/SummitDemo/blob/master/Analysis%20of%20Dance%20Moves.ipynb) about encoding time-series signals into **fixed length feature vectors for signal classification**. 
* Some basic signal modelling with **linear and polynomial regressions**. 
* Or **Spike/Anomaly Detection in time signals** using 1d convolutions like was done in some of the [CCX work](https://gitlab.cee.redhat.com/kachauha/kraken-core/-/blob/merge-requests/35/kraken_core/notebooks/spike_detection.ipynb) . 

I dunno. Just some ideas :smiley: WDYT?

**Comment by Shreyanand** [comment]
> What is the purpose of this project? To connect with real Prometheus data, then demo a number of time series analysis techniques similar to the categorical encoding work? If so, wouldn't a single "problem statement" artificially narrow the scope? Have you defined what techniques/things you want to cover in the "time series introduction material" yet?

That is correct: to demo a number of time series analysis techniques and Prometheus data. However, with a single problem what I aimed was to show that we could use all these techniques in an example real project. I added this issue so that while I'm working on the demo notebooks, I could start looking at an example problem that I could use likely at the end of the demos but still as a part of the project. If that seems out of the scope, let me know, I'll re-frame this issue to track techniques.

> 
> You might want to define a couple of problem statements like:
> 
> * Revisit some of the [Prometheus anomaly detection](https://github.com/AICoE/prometheus-anomaly-detector) work to **explore a number of time-series forecasting methods**.
> * Look at this [summit demo](https://github.com/TreeinRandomForest/SummitDemo/blob/master/Analysis%20of%20Dance%20Moves.ipynb) about encoding time-series signals into **fixed length feature vectors for signal classification**.
> * Some basic signal modelling with **linear and polynomial regressions**.
> * Or **Spike/Anomaly Detection in time signals** using 1d convolutions like was done in some of the [CCX work](https://gitlab.cee.redhat.com/kachauha/kraken-core/-/blob/merge-requests/35/kraken_core/notebooks/spike_detection.ipynb) .
> 
> I dunno. Just some ideas  WDYT?

These are great, I didn't know about the spike detection work and the summit demo, I'll look into it! Thanks for sharing :)

**Comment by MichaelClifford** [comment]
@Shreyanand can we close this issue for now?
