### ISSUE TITLE
Create a notebook comparing and describing techniques for forecasting time series

### ISSUE THREAD

**Issue by Shreyanand** [aicoe-aiops/time-series#9]
As a data scientist, for the next notebook in the time series blog posts, we would like to compare different forecasting methods on an example dataset of metrics.

Acceptance: 
A notebook with: 

- [ ] Application of different forecasting methods on an example dataset.

- [ ] Comparisons and plots highlighting performance of each method.

- [ ] A summary of results and conclusions derived from the experiments

Related issues: 
[Issue](https://github.com/aicoe-aiops/time-series/issues/8) 
[Issue](https://github.com/aicoe-aiops/cloud-price-analysis/issues/55)

**Comment by chauhankaranraj** [comment]
Another related issue is aicoe-aiops/ceph_drive_failure#11, closed by PR aicoe-aiops/ceph_drive_failure#12

The notebook which compares results from the different techniques: https://github.com/aicoe-aiops/ceph_drive_failure/blob/master/notebooks/experimental/forecast_smart_metrics.ipynb

cc @Shreyanand @aakankshaduggal

**Comment by Shreyanand** [comment]
Updates: 
- WIP notebook is up.
- To do:
  * Add decomposition and then trend prediction method
  * Add comparison error metrics
  * Put everything in functions, add comments, and improve plots
  * Add explanations and summary conclusion
